### PR TITLE
Dev branch

### PR DESCRIPTION
**Pull request by RoodzFernando**
This is my project submitted for reviews. Thanks!

### CODE REVIEW

**Comment by shloch** [comment]
### Pull request under review by SHEY LOUIS

**Comment by shloch** [comment]
### Changes Required 🤓
Hi @RoodzFernando 👋,

You've done a great job setting up this project so far. 😄

Please i need you to bring minor modifications
- the live demo link on the README file, not working, please update that (you can use `https://raw.githack.com/` to generate demo link)
- carry **ALL** inline styling into your CSS file. You did a lot of that, it's not good for maintenance

Your design is very fluid, good job. 

**### Do the minor changes and file for a re-view, and we'll be good** 

Happy coding

**Comment by RoodzFernando** [comment]
- I removed all the inlines style.
- The demo is not available yet before merging the branches. I can't generate one with the link you provided, but It will work after merging. Thank you!

**Review by suretrust — APPROVED** [review]
Hi @RoodzFernando,

Great job! :raised_hands: **Let's get this merged**. :tada: 

_Good luck with your future projects and happy coding!_

**Pull request merged**
